### ISSUE TITLE
demo.py

### ISSUE THREAD

**Issue by world2025** [kevinchan04/MA-SSD#3]
你好，感谢你的开源，不过我在运行demo的时候遇到了一个问题，Traceback (most recent call last):
  File "demo.py", line 130, in <module>
    main()
  File "demo.py", line 126, in main
    is_save=True)
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "demo.py", line 34, in run_demo
    checkpointer.load(ckpt, use_latest=ckpt is None)
  File "/app/MA-SSD/ssd/utils/checkpoint.py", line 68, in load
    model.load_state_dict(checkpoint.pop("model"))
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 847, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for SSDDetector:
	Unexpected key(s) in state_dict: "neck.my_sp_attention.0.0.weight", "neck.my_sp_attention.0.1.weight", "neck.my_sp_attention.0.1.bias", "neck.my_sp_attention.0.1.running_mean", "neck.my_sp_attention.0.1.running_var", "neck.my_sp_attention.0.1.num_batches_tracked", "neck.my_sp_attention.0.3.weight", "neck.my_sp_attention.0.3.bias", "neck.my_sp_attention.0.4.weight", "neck.my_sp_attention.0.4.bias", "neck.my_sp_attention.0.4.running_mean", "neck.my_sp_attention.0.4.running_var", "neck.my_sp_attention.0.4.num_batches_tracked", "neck.my_sp_attention.0.6.weight", "neck.my_sp_attention.0.6.bias", "neck.my_sp_attention.0.7.weight", "neck.my_sp_attention.0.7.bias", "neck.my_sp_attention.0.7.running_mean", "neck.my_sp_attention.0.7.running_var", "neck.my_sp_attention.0.7.num_batches_tracked", "neck.my_sp_attention.0.9.weight", "neck.my_sp_attention.1.0.weight", "neck.my_sp_attention.1.1.weight", "neck.my_sp_attention.1.1.bias", "neck.my_sp_attention.1.1.running_mean", "neck.my_sp_attention.1.1.running_var", "neck.my_sp_attention.1.1.num_batches_tracked", "neck.my_sp_attention.1.3.weight", "neck.my_sp_attention.1.3.bias", "neck.my_sp_attention.1.4.weight", "neck.my_sp_attention.1.4.bias", "neck.my_sp_attention.1.4.running_mean", "neck.my_sp_attention.1.4.running_var", "neck.my_sp_attention.1.4.num_batches_tracked", "neck.my_sp_attention.1.6.weight", "neck.my_sp_attention.1.6.bias", "neck.my_sp_attention.1.7.weight", "neck.my_sp_attention.1.7.bias", "neck.my_sp_attention.1.7.running_mean", "neck.my_sp_attention.1.7.running_var", "neck.my_sp_attention.1.7.num_batches_tracked", "neck.my_sp_attention.1.9.weight", "neck.conv1x1_ch.0.weight", "neck.conv1x1_ch.0.bias", "neck.my_ch_attention.0.0.weight", "neck.my_ch_attention.0.2.weight", "neck.my_deconv.0.0.weight", "neck.my_deconv.0.0.bias", "neck.my_deconv.0.1.weight", "neck.my_deconv.0.1.bias", "neck.my_deconv.0.1.running_mean", "neck.my_deconv.0.1.running_var", "neck.my_deconv.0.1.num_batches_tracked", "neck.my_deconv.1.0.weight", "neck.my_deconv.1.0.bias", "neck.my_deconv.1.1.weight", "neck.my_deconv.1.1.bias", "neck.my_deconv.1.1.running_mean", "neck.my_deconv.1.1.running_var", "neck.my_deconv.1.1.num_batches_tracked". 
	size mismatch for box_head.predictor.cls_headers.0.weight: copying a param with shape torch.Size([126, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([84, 512, 3, 3]).
	size mismatch for box_head.predictor.cls_headers.0.bias: copying a param with shape torch.Size([126]) from checkpoint, the shape in current model is torch.Size([84]).
我不知道是不是因为torch版本的原因导致加载模型错误，还麻烦你看看哈，我的torch版本是1.5

**Comment by kevinchan04** [comment]
Please try it : `python demo.py --config-file configs/vgg_att_ssd300_neckthreemed_voc0712.yaml --images_dir demo --ckpt https://github.com/kevinchan04/MA-SSD/releases/download/1.0/vgg_att_ssd300_voc0712_neckthreemed.pth` . Sorry for the late reply. I think it is not a problem about the version of pytorch. It is my typo. Sorry about it.
